version: "2.4"
services:

  $$NAME$$:
    container_name: $$NAME$$
    image: mobicoop/php-node-chromium:2.0.0
    # build: ./
    ports:
      - '9089:9089'
      - '9091:9091'
    working_dir: /var/www
    entrypoint: zsh /var/www/entrypoint.sh
    tty: true
    environment:
      - COMPOSER_PROCESS_TIMEOUT=1200
    volumes:
      - ./:/var/www:cached
      - ${MOBICOOP_CLIENT:?You forgot to indicate the env MOBICOOP_CLIENT inside bashrc or zshrc}:/var/client:cached
    networks:
      - mobicoop_platform

networks:
  mobicoop_platform:
    external: true