<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200211111522 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DELETE FROM role_right;');
        $this->addSql('DELETE FROM user_right;');
        $this->addSql('DELETE FROM uright;');
        $this->addSql('
            INSERT INTO `uright` (`id`, `name`, `description`, `object`) VALUES
            (1, \'user_manage\', \'Manage users\', NULL),
            (2, \'user_car_manage\', \'Manage users cars\', NULL),
            (3, \'user_address_manage\', \'Manage users addresses\', NULL),
            (4, \'user_message_manage\', \'Manage users messages\', NULL),
            (5, \'user_manage_self\', \'Manage its own profile\', NULL),
            (6, \'user_car_manage_self\', \'Manage its own cars\', NULL),
            (7, \'user_address_manage_self\', \'Manage its own addresses\', NULL),
            (8, \'user_message_manage_self\', \'Manage its own messages\', NULL),
            (9, \'carpool_manage\', \'Manage carpool data\', NULL),
            (10, \'carpool_manage_self\', \'Manage its own carpool data\', NULL),
            (11, \'article_manage\', \'Manage articles\', NULL),
            (12, \'community_manage\', \'Manage communities\', NULL),
            (13, \'community_manage_self\', \'Manage its own communities\', NULL),
            (14, \'event_manage\', \'Manage events\', NULL),
            (15, \'event_manage_self\', \'Manage its own events\', NULL),
            (16, \'relay_point_manage\', \'Manage relay points\', NULL),
            (17, \'relay_point_manage_self\', \'Manage its own relay points\', NULL),
            (18, \'territory_manage\', \'Manage territories\', NULL),
            (19, \'mass_manage\', \'Manage mass matching data\', NULL),
            (20, \'permission_manage\', \'Manage permissions\', NULL),
            (21, \'solidary_manage\', \'Manage solidary data\', NULL),
            (22, \'mass_communication_manage\', \'Manage communication campaigns\', NULL),
            (23, \'mass_communication_manage_self\', \'Manage its own communication campaigns\', NULL),
            (24, \'user_register\', \'Minimal registration\', NULL),
            (25, \'user_register_full\', \'Full registration\', NULL),
            (26, \'user_create\', \'Create a user\', NULL),
            (27, \'user_update\', \'Update a user\', NULL),
            (28, \'user_delete\', \'Delete a user\', NULL),
            (29, \'user_password\', \'Change user password\', NULL),
            (30, \'user_car_create\', \'Create a car for a user\', NULL),
            (31, \'user_car_update\', \'Update a car for a user\', NULL),
            (32, \'user_car_delete\', \'Delete a car for a user\', NULL),
            (33, \'user_address_create\', \'Create an address for a user\', NULL),
            (34, \'user_address_update\', \'Update an address for a user\', NULL),
            (35, \'user_address_delete\', \'Delete an address for a user\', NULL),
            (36, \'user_message_read\', \'Read the messages of a user\', NULL),
            (37, \'user_message_delete\', \'Delete the messages of a user\', NULL),
            (38, \'user_update_self\', \'Update its own profile\', \'user\'),
            (39, \'user_delete_self\', \'Delete its own profile\', \'user\'),
            (40, \'user_password_self\', \'Change its own password\', \'user\'),
            (41, \'user_car_create_self\', \'Create a car for itself\', NULL),
            (42, \'user_car_update_self\', \'Update its own car\', \'user\'),
            (43, \'user_car_delete_self\', \'Delete its own car\', \'user\'),
            (44, \'user_address_create_self\', \'Create an address for itself\', NULL),
            (45, \'user_address_update_self\', \'Update its own address\', \'user\'),
            (46, \'user_address_delete_self\', \'Delete its own address\', \'user\'),
            (47, \'user_message_create\', \'Create a message\', NULL),
            (48, \'user_message_read_self\', \'Read its own messages\', \'user\'),
            (49, \'user_message_delete_self\', \'Delete its own messages\', \'user\'),
            (50, \'ad_read\', \'View a user ad\', NULL),
            (51, \'ad_create\', \'Create an ad for a user\', NULL),
            (52, \'ad_update\', \'Update an ad for a user\', NULL),
            (53, \'ad_delete\', \'Delete an ad for a user\', NULL),
            (54, \'ad_search\', \'Search an ad\', NULL),
            (55, \'ad_create_self\', \'Create its own ad\', NULL),
            (56, \'ad_update_self\', \'Update its own ad\', \'ad\'),
            (57, \'ad_delete_self\', \'Delete its own address\', \'ad\'),
            (58, \'ad_results_self\', \'View the results of its own ad\', \'ad\'),
            (59, \'article_create\', \'Create an article\', NULL),
            (60, \'article_update\', \'Update an article\', NULL),
            (61, \'article_delete\', \'Delete an article\', NULL),
            (62, \'article_read\', \'Read an article\', NULL),
            (63, \'community_list\', \'View the list of communities\', NULL),
            (64, \'community_read\', \'View a community\', NULL),
            (65, \'community_create\', \'Create a community\', NULL),
            (66, \'community_private_create\', \'Create a private community\', NULL),
            (67, \'community_update\', \'Update a community\', NULL),
            (68, \'community_delete\', \'Delete a community\', NULL),
            (69, \'community_member_accept\', \'Accept a member in a community\', NULL),
            (70, \'community_member_refuse\', \'Refuse a member in a community\', NULL),
            (71, \'community_update_self\', \'Update its own community\', \'community\'),
            (72, \'community_delete_self\', \'Delete its own community\', \'community\'),
            (73, \'community_join\', \'Join a community\', NULL),
            (74, \'community_join_private\', \'Join a private community\', NULL),
            (75, \'community_leave\', \'Leave a community\', NULL),
            (76, \'event_list\', \'View the list of events\', NULL),
            (77, \'event_read\', \'View an event\', NULL),
            (78, \'event_create\', \'Create an event\', NULL),
            (79, \'event_update\', \'Update an event\', NULL),
            (80, \'event_delete\', \'Delete an event\', NULL),
            (81, \'event_update_self\', \'Update its own event\', \'event\'),
            (82, \'event_delete_self\', \'Delete its own event\', \'event\'),
            (83, \'relay_point_read\', \'View a relay point\', NULL),
            (84, \'relay_point_create\', \'Create a relay point\', NULL),
            (85, \'relay_point_update\', \'Update a relay point\', NULL),
            (86, \'relay_point_delete\', \'Delete a relay point\', NULL),
            (87, \'relay_point_update_self\', \'Update its own relay point\', \'relaypoint\'),
            (88, \'relay_point_delete_self\', \'Delete its own relay point\', \'relaypoint\'),
            (89, \'relay_point_type_create\', \'Create a relay point type\', NULL),
            (90, \'relay_point_type_update\', \'Update a relay point type\', NULL),
            (91, \'relay_point_type_delete\', \'Delete a relay point type\', NULL),
            (92, \'relay_point_type_update_self\', \'Update its own relay point type\', \'relaypointtype\'),
            (93, \'relay_point_type_delete_self\', \'Delete its own relay point type\', \'relaypointtype\'),
            (94, \'territory_create\', \'Create a territory\', NULL),
            (95, \'territory_update\', \'Update a territory\', NULL),
            (96, \'territory_delete\', \'Delete a territory\', NULL),
            (97, \'mass_create\', \'Create mass matching data\', NULL),
            (98, \'mass_read\', \'Read a mass matching data\', NULL),
            (99, \'mass_delete\', \'Delete mass matching data\', NULL),
            (100, \'role_assign\', \'Assign a role to a user\', NULL),
            (101, \'right_role_assign\', \'Assign a right to a role\', NULL),
            (102, \'right_user_assign\', \'Assign a right to a user\', NULL),
            (103, \'solidary_create\', \'Create a solidary record\', NULL),
            (104, \'solidary_read\', \'Read a solidary record\', NULL),
            (105, \'solidary_update\', \'Update a solidary record\', NULL),
            (106, \'solidary_delete\', \'Delete a solidary record\', NULL),
            (107, \'campaign_read\', \'View a campaign\', NULL),
            (108, \'campaign_create\', \'Create a campaign\', NULL),
            (109, \'campaign_update\', \'Update a campaign\', NULL),
            (110, \'campaign_delete\', \'Delete a campaign\', NULL),
            (111, \'campaign_read_self\', \'View its own campaign\', \'campaign\'),
            (112, \'campaign_update_self\', \'Update its own campaign\', \'campaign\'),
            (113, \'campaign_delete_self\', \'Delete its own campaign\', \'campaign\'),
            (114, \'check_permission\', \'Check permission\', NULL),
            (115, \'check_permission_self\', \'Check permission for its own objects\', NULL),
            (116, \'access_admin\', \'Get access to administration\', NULL),
            (117, \'ad_results\', \'View the results of an ad\', NULL);
        ');
        $this->addSql('
            INSERT INTO `right_right` (`right_source`, `right_target`) VALUES
            (26,1),
            (27,1),
            (27,38),
            (28,1),
            (28,39),
            (29,1),
            (29,40),
            (30,2),
            (30,41),
            (31,2),
            (31,42),
            (32,2),
            (32,43),
            (33,3),
            (33,44),
            (34,3),
            (34,45),
            (35,3),
            (35,46),
            (36,4),
            (36,48),
            (37,4),
            (37,49),
            (38,5),
            (39,5),
            (40,5),
            (41,6),
            (42,6),
            (43,6),
            (44,7),
            (45,7),
            (46,7),
            (47,8),
            (48,8),
            (49,8),
            (50,9),
            (51,9),
            (51,5),
            (52,9),
            (52,56),
            (53,9),
            (53,57),
            (55,10),
            (56,10),
            (57,10),
            (58,10),
            (59,11),
            (60,11),
            (61,11),
            (65,12),
            (66,12),
            (67,12),
            (67,71),
            (68,12),
            (68,72),
            (69,12),
            (70,12),
            (71,13),
            (72,13),
            (79,14),
            (79,81),
            (80,14),
            (80,82),
            (81,15),
            (82,15),
            (85,16),
            (85,87),
            (86,16),
            (86,88),
            (87,17),
            (88,17),
            (89,16),
            (90,16),
            (90,92),
            (91,16),
            (91,93),
            (92,17),
            (93,17),
            (94,18),
            (95,18),
            (96,18),
            (97,19),
            (98,19),
            (99,19),
            (100,20),
            (101,20),
            (102,20),
            (103,21),
            (104,21),
            (105,21),
            (106,21),
            (107,22),
            (107,111),
            (108,22),
            (109,22),
            (109,112),
            (110,22),
            (110,113),
            (111,23),
            (112,23),
            (113,23),
            (114,20),
            (117,9),
            (117, 58);
        ');
        $this->addSql('
            INSERT INTO `role_right` (`role_id`, `right_id`) VALUES
            (1, 20),
            (2, 1),
            (2, 2),
            (2, 3),
            (2, 4),
            (2, 9),
            (2, 11),
            (2, 12),
            (2, 14),
            (2, 16),
            (2, 18),
            (2, 21),
            (2, 22),
            (2, 114),
            (2, 116),
            (3, 6),
            (3, 7),
            (3, 13),
            (3, 15),
            (3, 17),
            (3, 65),
            (3, 73),
            (3, 74),
            (3, 75),
            (3, 78),
            (3, 84),
            (3, 89),
            (4, 5),
            (4, 8),
            (4, 10),
            (4, 115),
            (5, 24),
            (5, 25),
            (5, 54),
            (5, 62),
            (5, 63),
            (5, 64),
            (5, 76),
            (5, 77),
            (5, 83),
            (6, 19);
        ');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    }
}
