<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190809125406 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, action_id INT NOT NULL, admin_id INT DEFAULT NULL, proposal_id INT DEFAULT NULL, matching_id INT DEFAULT NULL, ask_id INT DEFAULT NULL, article_id INT DEFAULT NULL, event_id INT DEFAULT NULL, community_id INT DEFAULT NULL, solidary_id INT DEFAULT NULL, territory_id INT DEFAULT NULL, car_id INT DEFAULT NULL, user_related_id INT DEFAULT NULL, message_id INT DEFAULT NULL, date DATETIME NOT NULL, INDEX IDX_8F3F68C5A76ED395 (user_id), INDEX IDX_8F3F68C59D32F035 (action_id), INDEX IDX_8F3F68C5642B8210 (admin_id), INDEX IDX_8F3F68C5F4792058 (proposal_id), INDEX IDX_8F3F68C5B39876B8 (matching_id), INDEX IDX_8F3F68C5B93F8B63 (ask_id), INDEX IDX_8F3F68C57294869C (article_id), INDEX IDX_8F3F68C571F7E88B (event_id), INDEX IDX_8F3F68C5FDA7B0BF (community_id), INDEX IDX_8F3F68C5E92CE751 (solidary_id), INDEX IDX_8F3F68C573F74AD4 (territory_id), INDEX IDX_8F3F68C5C3C6F69F (car_id), INDEX IDX_8F3F68C5E60506ED (user_related_id), INDEX IDX_8F3F68C5537A1329 (message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE solidary_matching (id INT AUTO_INCREMENT NOT NULL, matching_id INT NOT NULL, solidary_id INT NOT NULL, created_date DATETIME NOT NULL, INDEX IDX_A95C6411B39876B8 (matching_id), INDEX IDX_A95C6411E92CE751 (solidary_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE structure (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE solidary (id INT AUTO_INCREMENT NOT NULL, proposal_id INT NOT NULL, user_id INT NOT NULL, status SMALLINT NOT NULL, assisted TINYINT(1) DEFAULT NULL, structure VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, created_date DATETIME NOT NULL, INDEX IDX_1896BCA4F4792058 (proposal_id), INDEX IDX_1896BCA4A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subject (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE diary (id INT AUTO_INCREMENT NOT NULL, action_id INT NOT NULL, user_id INT NOT NULL, admin_id INT NOT NULL, solidary_id INT DEFAULT NULL, solidary_matching_id INT DEFAULT NULL, created_date DATETIME NOT NULL, INDEX IDX_917BEDE29D32F035 (action_id), INDEX IDX_917BEDE2A76ED395 (user_id), INDEX IDX_917BEDE2642B8210 (admin_id), INDEX IDX_917BEDE2E92CE751 (solidary_id), INDEX IDX_917BEDE218E9BFA2 (solidary_matching_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C59D32F035 FOREIGN KEY (action_id) REFERENCES action (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5642B8210 FOREIGN KEY (admin_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5F4792058 FOREIGN KEY (proposal_id) REFERENCES proposal (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5B39876B8 FOREIGN KEY (matching_id) REFERENCES matching (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5B93F8B63 FOREIGN KEY (ask_id) REFERENCES ask (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C57294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C571F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5FDA7B0BF FOREIGN KEY (community_id) REFERENCES community (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5E92CE751 FOREIGN KEY (solidary_id) REFERENCES solidary (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C573F74AD4 FOREIGN KEY (territory_id) REFERENCES territory (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5C3C6F69F FOREIGN KEY (car_id) REFERENCES car (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5E60506ED FOREIGN KEY (user_related_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5537A1329 FOREIGN KEY (message_id) REFERENCES message (id)');
        $this->addSql('ALTER TABLE solidary_matching ADD CONSTRAINT FK_A95C6411B39876B8 FOREIGN KEY (matching_id) REFERENCES matching (id)');
        $this->addSql('ALTER TABLE solidary_matching ADD CONSTRAINT FK_A95C6411E92CE751 FOREIGN KEY (solidary_id) REFERENCES solidary (id)');
        $this->addSql('ALTER TABLE solidary ADD CONSTRAINT FK_1896BCA4F4792058 FOREIGN KEY (proposal_id) REFERENCES proposal (id)');
        $this->addSql('ALTER TABLE solidary ADD CONSTRAINT FK_1896BCA4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE diary ADD CONSTRAINT FK_917BEDE29D32F035 FOREIGN KEY (action_id) REFERENCES action (id)');
        $this->addSql('ALTER TABLE diary ADD CONSTRAINT FK_917BEDE2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE diary ADD CONSTRAINT FK_917BEDE2642B8210 FOREIGN KEY (admin_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE diary ADD CONSTRAINT FK_917BEDE2E92CE751 FOREIGN KEY (solidary_id) REFERENCES solidary (id)');
        $this->addSql('ALTER TABLE diary ADD CONSTRAINT FK_917BEDE218E9BFA2 FOREIGN KEY (solidary_matching_id) REFERENCES solidary_matching (id)');
        $this->addSql('ALTER TABLE action ADD in_log TINYINT(1) DEFAULT NULL, ADD in_diary TINYINT(1) DEFAULT NULL, ADD progression INT DEFAULT NULL, DROP uname');
        $this->addSql('ALTER TABLE app CHANGE password password VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE section CHANGE article_id article_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE sub_title sub_title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE paragraph CHANGE section_id section_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ask_history CHANGE ask_id ask_id INT DEFAULT NULL, CHANGE message_id message_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ask ADD user_delegate_id INT DEFAULT NULL, CHANGE ask_linked_id ask_linked_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ask ADD CONSTRAINT FK_6826EAE023107D10 FOREIGN KEY (user_delegate_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_6826EAE023107D10 ON ask (user_delegate_id)');
        $this->addSql('ALTER TABLE criteria CHANGE car_id car_id INT DEFAULT NULL, CHANGE direction_driver_id direction_driver_id INT DEFAULT NULL, CHANGE direction_passenger_id direction_passenger_id INT DEFAULT NULL, CHANGE ptjourney_id ptjourney_id INT DEFAULT NULL, CHANGE from_time from_time TIME DEFAULT NULL, CHANGE to_date to_date DATE DEFAULT NULL, CHANGE mon_check mon_check TINYINT(1) DEFAULT NULL, CHANGE tue_check tue_check TINYINT(1) DEFAULT NULL, CHANGE wed_check wed_check TINYINT(1) DEFAULT NULL, CHANGE thu_check thu_check TINYINT(1) DEFAULT NULL, CHANGE fri_check fri_check TINYINT(1) DEFAULT NULL, CHANGE sat_check sat_check TINYINT(1) DEFAULT NULL, CHANGE sun_check sun_check TINYINT(1) DEFAULT NULL, CHANGE mon_time mon_time TIME DEFAULT NULL, CHANGE tue_time tue_time TIME DEFAULT NULL, CHANGE wed_time wed_time TIME DEFAULT NULL, CHANGE thu_time thu_time TIME DEFAULT NULL, CHANGE fri_time fri_time TIME DEFAULT NULL, CHANGE sat_time sat_time TIME DEFAULT NULL, CHANGE sun_time sun_time TIME DEFAULT NULL, CHANGE multi_transport_mode multi_transport_mode TINYINT(1) DEFAULT NULL, CHANGE price_km price_km NUMERIC(4, 2) DEFAULT NULL, CHANGE max_detour_duration max_detour_duration INT DEFAULT NULL, CHANGE max_detour_distance max_detour_distance INT DEFAULT NULL, CHANGE min_time min_time TIME DEFAULT NULL, CHANGE max_time max_time TIME DEFAULT NULL, CHANGE mon_min_time mon_min_time TIME DEFAULT NULL, CHANGE mon_max_time mon_max_time TIME DEFAULT NULL, CHANGE tue_min_time tue_min_time TIME DEFAULT NULL, CHANGE tue_max_time tue_max_time TIME DEFAULT NULL, CHANGE wed_min_time wed_min_time TIME DEFAULT NULL, CHANGE wed_max_time wed_max_time TIME DEFAULT NULL, CHANGE thu_min_time thu_min_time TIME DEFAULT NULL, CHANGE thu_max_time thu_max_time TIME DEFAULT NULL, CHANGE fri_min_time fri_min_time TIME DEFAULT NULL, CHANGE fri_max_time fri_max_time TIME DEFAULT NULL, CHANGE sat_min_time sat_min_time TIME DEFAULT NULL, CHANGE sat_max_time sat_max_time TIME DEFAULT NULL, CHANGE sun_min_time sun_min_time TIME DEFAULT NULL, CHANGE sun_max_time sun_max_time TIME DEFAULT NULL, CHANGE margin_duration margin_duration INT DEFAULT NULL, CHANGE mon_margin_duration mon_margin_duration INT DEFAULT NULL, CHANGE tue_margin_duration tue_margin_duration INT DEFAULT NULL, CHANGE wed_margin_duration wed_margin_duration INT DEFAULT NULL, CHANGE thu_margin_duration thu_margin_duration INT DEFAULT NULL, CHANGE fri_margin_duration fri_margin_duration INT DEFAULT NULL, CHANGE sat_margin_duration sat_margin_duration INT DEFAULT NULL, CHANGE sun_margin_duration sun_margin_duration INT DEFAULT NULL, CHANGE driver driver TINYINT(1) DEFAULT NULL, CHANGE passenger passenger TINYINT(1) DEFAULT NULL');
        // --
        // patch for foreign key user_id field in proposal changing from nullable to not null
        $this->addSql('ALTER TABLE proposal DROP FOREIGN KEY FK_BFE59472A76ED395');
        // original statement
        $this->addSql('ALTER TABLE proposal ADD user_delegate_id INT DEFAULT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE proposal_linked_id proposal_linked_id INT DEFAULT NULL, CHANGE criteria_id criteria_id INT DEFAULT NULL');
        // end patch
        $this->addSql('ALTER TABLE proposal ADD CONSTRAINT FK_BFE59472A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        // --
        $this->addSql('ALTER TABLE proposal ADD CONSTRAINT FK_BFE5947223107D10 FOREIGN KEY (user_delegate_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_BFE5947223107D10 ON proposal (user_delegate_id)');
        $this->addSql('ALTER TABLE waypoint CHANGE proposal_id proposal_id INT DEFAULT NULL, CHANGE matching_id matching_id INT DEFAULT NULL, CHANGE ask_id ask_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE message CHANGE message_id message_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE notified CHANGE proposal_id proposal_id INT DEFAULT NULL, CHANGE matching_id matching_id INT DEFAULT NULL, CHANGE ask_history_id ask_history_id INT DEFAULT NULL, CHANGE recipient_id recipient_id INT DEFAULT NULL, CHANGE sent_date sent_date DATETIME DEFAULT NULL, CHANGE received_date received_date DATETIME DEFAULT NULL, CHANGE read_date read_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE recipient CHANGE read_date read_date DATETIME DEFAULT NULL, CHANGE sent_date sent_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE notification CHANGE template_title template_title VARCHAR(255) DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT NULL, CHANGE active_default active_default TINYINT(1) DEFAULT NULL, CHANGE template_body template_body VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE community_user CHANGE admin_id admin_id INT DEFAULT NULL, CHANGE accepted_date accepted_date DATETIME DEFAULT NULL, CHANGE refused_date refused_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE community CHANGE members_hidden members_hidden TINYINT(1) DEFAULT NULL, CHANGE proposals_hidden proposals_hidden TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE event CHANGE url url VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE address CHANGE user_id user_id INT DEFAULT NULL, CHANGE street_address street_address VARCHAR(255) DEFAULT NULL, CHANGE postal_code postal_code VARCHAR(15) DEFAULT NULL, CHANGE address_locality address_locality VARCHAR(100) DEFAULT NULL, CHANGE address_country address_country VARCHAR(100) DEFAULT NULL, CHANGE latitude latitude NUMERIC(10, 6) DEFAULT NULL, CHANGE longitude longitude NUMERIC(10, 6) DEFAULT NULL, CHANGE elevation elevation INT DEFAULT NULL, CHANGE name name VARCHAR(45) DEFAULT NULL, CHANGE house_number house_number VARCHAR(45) DEFAULT NULL, CHANGE street street VARCHAR(255) DEFAULT NULL, CHANGE sub_locality sub_locality VARCHAR(100) DEFAULT NULL, CHANGE local_admin local_admin VARCHAR(100) DEFAULT NULL, CHANGE county county VARCHAR(100) DEFAULT NULL, CHANGE macro_county macro_county VARCHAR(100) DEFAULT NULL, CHANGE region region VARCHAR(100) DEFAULT NULL, CHANGE macro_region macro_region VARCHAR(100) DEFAULT NULL, CHANGE country_code country_code VARCHAR(10) DEFAULT NULL, CHANGE geo_json geo_json POINT DEFAULT NULL COMMENT \'(DC2Type:point)\', CHANGE home home TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE direction CHANGE ascend ascend INT DEFAULT NULL, CHANGE descend descend INT DEFAULT NULL, CHANGE bbox_min_lon bbox_min_lon NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_min_lat bbox_min_lat NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_max_lon bbox_max_lon NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_max_lat bbox_max_lat NUMERIC(10, 6) DEFAULT NULL, CHANGE bearing bearing INT DEFAULT NULL, CHANGE geo_json_bbox geo_json_bbox POLYGON DEFAULT NULL COMMENT \'(DC2Type:polygon)\', CHANGE geo_json_detail geo_json_detail LINESTRING DEFAULT NULL COMMENT \'(DC2Type:linestring)\'');
        $this->addSql('ALTER TABLE image CHANGE event_id event_id INT DEFAULT NULL, CHANGE community_id community_id INT DEFAULT NULL, CHANGE relay_point_id relay_point_id INT DEFAULT NULL, CHANGE relay_point_type_id relay_point_type_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE alt alt VARCHAR(255) DEFAULT NULL, CHANGE crop_x1 crop_x1 INT DEFAULT NULL, CHANGE crop_y1 crop_y1 INT DEFAULT NULL, CHANGE crop_x2 crop_x2 INT DEFAULT NULL, CHANGE crop_y2 crop_y2 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mass CHANGE calculation_date calculation_date DATETIME DEFAULT NULL, CHANGE analyzing_date analyzing_date DATETIME DEFAULT NULL, CHANGE analyzed_date analyzed_date DATETIME DEFAULT NULL, CHANGE calculated_date calculated_date DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE mass_person CHANGE given_name given_name VARCHAR(255) DEFAULT NULL, CHANGE family_name family_name VARCHAR(255) DEFAULT NULL, CHANGE outward_time outward_time TIME DEFAULT NULL, CHANGE return_time return_time TIME DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE bbox_min_lon bbox_min_lon NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_min_lat bbox_min_lat NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_max_lon bbox_max_lon NUMERIC(10, 6) DEFAULT NULL, CHANGE bbox_max_lat bbox_max_lat NUMERIC(10, 6) DEFAULT NULL, CHANGE bearing bearing INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ptleg CHANGE ptjourney_id ptjourney_id INT DEFAULT NULL, CHANGE ptdeparture_id ptdeparture_id INT DEFAULT NULL, CHANGE ptarrival_id ptarrival_id INT DEFAULT NULL, CHANGE travel_mode_id travel_mode_id INT DEFAULT NULL, CHANGE ptline_id ptline_id INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE magnetic_direction magnetic_direction VARCHAR(10) DEFAULT NULL, CHANGE relative_direction relative_direction VARCHAR(10) DEFAULT NULL, CHANGE direction direction VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE ptline CHANGE ptcompany_id ptcompany_id INT DEFAULT NULL, CHANGE travel_mode_id travel_mode_id INT DEFAULT NULL, CHANGE number number VARCHAR(10) DEFAULT NULL, CHANGE origin origin VARCHAR(100) DEFAULT NULL, CHANGE destination destination VARCHAR(100) DEFAULT NULL, CHANGE direction direction VARCHAR(255) DEFAULT NULL, CHANGE transport_mode transport_mode INT DEFAULT NULL, CHANGE color color VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE ptstep CHANGE ptleg_id ptleg_id INT DEFAULT NULL, CHANGE ptdeparture_id ptdeparture_id INT DEFAULT NULL, CHANGE ptarrival_id ptarrival_id INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE magnetic_direction magnetic_direction VARCHAR(10) DEFAULT NULL, CHANGE relative_direction relative_direction VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE ptdeparture CHANGE individual_stop_id individual_stop_id INT DEFAULT NULL, CHANGE name name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE ptarrival CHANGE individual_stop_id individual_stop_id INT DEFAULT NULL, CHANGE name name VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE ptjourney CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration VARCHAR(100) DEFAULT NULL, CHANGE price price NUMERIC(4, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE relay_point CHANGE community_id community_id INT DEFAULT NULL, CHANGE private private TINYINT(1) DEFAULT NULL, CHANGE places places SMALLINT DEFAULT NULL, CHANGE places_disabled places_disabled SMALLINT DEFAULT NULL, CHANGE free free TINYINT(1) DEFAULT NULL, CHANGE secured secured TINYINT(1) DEFAULT NULL, CHANGE official official TINYINT(1) DEFAULT NULL, CHANGE suggested suggested TINYINT(1) DEFAULT NULL, CHANGE permalink permalink VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE uright CHANGE parent_id parent_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE role CHANGE parent_id parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_right CHANGE territory_id territory_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_role CHANGE territory_id territory_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user ADD pwd_token_date DATETIME DEFAULT NULL, DROP pupdtime, CHANGE given_name given_name VARCHAR(100) DEFAULT NULL, CHANGE family_name family_name VARCHAR(100) DEFAULT NULL, CHANGE password password VARCHAR(100) DEFAULT NULL, CHANGE nationality nationality VARCHAR(100) DEFAULT NULL, CHANGE birth_date birth_date DATE DEFAULT NULL, CHANGE telephone telephone VARCHAR(100) DEFAULT NULL, CHANGE any_route_as_passenger any_route_as_passenger TINYINT(1) DEFAULT NULL, CHANGE multi_transport_mode multi_transport_mode TINYINT(1) DEFAULT NULL, CHANGE max_detour_duration max_detour_duration INT DEFAULT NULL, CHANGE max_detour_distance max_detour_distance INT DEFAULT NULL, CHANGE pwd_token pwd_token VARCHAR(100) DEFAULT NULL, CHANGE geo_token geo_token VARCHAR(100) DEFAULT NULL, CHANGE language language VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE car CHANGE color color VARCHAR(45) DEFAULT NULL, CHANGE siv siv VARCHAR(45) DEFAULT NULL, CHANGE price_km price_km NUMERIC(4, 2) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE diary DROP FOREIGN KEY FK_917BEDE218E9BFA2');
        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C5E92CE751');
        $this->addSql('ALTER TABLE solidary_matching DROP FOREIGN KEY FK_A95C6411E92CE751');
        $this->addSql('ALTER TABLE diary DROP FOREIGN KEY FK_917BEDE2E92CE751');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE solidary_matching');
        $this->addSql('DROP TABLE structure');
        $this->addSql('DROP TABLE solidary');
        $this->addSql('DROP TABLE subject');
        $this->addSql('DROP TABLE diary');
        $this->addSql('ALTER TABLE action ADD uname VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, DROP in_log, DROP in_diary, DROP progression');
        $this->addSql('ALTER TABLE address CHANGE user_id user_id INT DEFAULT NULL, CHANGE house_number house_number VARCHAR(45) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE street street VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE street_address street_address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE postal_code postal_code VARCHAR(15) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE sub_locality sub_locality VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE address_locality address_locality VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE local_admin local_admin VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE county county VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE macro_county macro_county VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE region region VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE macro_region macro_region VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE address_country address_country VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE country_code country_code VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE latitude latitude NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE longitude longitude NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE elevation elevation INT DEFAULT NULL, CHANGE geo_json geo_json POINT DEFAULT \'NULL\' COMMENT \'(DC2Type:point)\', CHANGE name name VARCHAR(45) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE home home TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE app CHANGE password password VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ask DROP FOREIGN KEY FK_6826EAE023107D10');
        $this->addSql('DROP INDEX IDX_6826EAE023107D10 ON ask');
        $this->addSql('ALTER TABLE ask DROP user_delegate_id, CHANGE ask_linked_id ask_linked_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ask_history CHANGE ask_id ask_id INT DEFAULT NULL, CHANGE message_id message_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE car CHANGE color color VARCHAR(45) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE siv siv VARCHAR(45) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE price_km price_km NUMERIC(4, 2) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE community CHANGE members_hidden members_hidden TINYINT(1) DEFAULT \'NULL\', CHANGE proposals_hidden proposals_hidden TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE community_user CHANGE admin_id admin_id INT DEFAULT NULL, CHANGE accepted_date accepted_date DATETIME DEFAULT \'NULL\', CHANGE refused_date refused_date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE criteria CHANGE car_id car_id INT DEFAULT NULL, CHANGE direction_driver_id direction_driver_id INT DEFAULT NULL, CHANGE direction_passenger_id direction_passenger_id INT DEFAULT NULL, CHANGE ptjourney_id ptjourney_id INT DEFAULT NULL, CHANGE driver driver TINYINT(1) DEFAULT \'NULL\', CHANGE passenger passenger TINYINT(1) DEFAULT \'NULL\', CHANGE from_time from_time TIME DEFAULT \'NULL\', CHANGE min_time min_time TIME DEFAULT \'NULL\', CHANGE max_time max_time TIME DEFAULT \'NULL\', CHANGE margin_duration margin_duration INT DEFAULT NULL, CHANGE to_date to_date DATE DEFAULT \'NULL\', CHANGE mon_check mon_check TINYINT(1) DEFAULT \'NULL\', CHANGE tue_check tue_check TINYINT(1) DEFAULT \'NULL\', CHANGE wed_check wed_check TINYINT(1) DEFAULT \'NULL\', CHANGE thu_check thu_check TINYINT(1) DEFAULT \'NULL\', CHANGE fri_check fri_check TINYINT(1) DEFAULT \'NULL\', CHANGE sat_check sat_check TINYINT(1) DEFAULT \'NULL\', CHANGE sun_check sun_check TINYINT(1) DEFAULT \'NULL\', CHANGE mon_time mon_time TIME DEFAULT \'NULL\', CHANGE mon_min_time mon_min_time TIME DEFAULT \'NULL\', CHANGE mon_max_time mon_max_time TIME DEFAULT \'NULL\', CHANGE tue_time tue_time TIME DEFAULT \'NULL\', CHANGE tue_min_time tue_min_time TIME DEFAULT \'NULL\', CHANGE tue_max_time tue_max_time TIME DEFAULT \'NULL\', CHANGE wed_time wed_time TIME DEFAULT \'NULL\', CHANGE wed_min_time wed_min_time TIME DEFAULT \'NULL\', CHANGE wed_max_time wed_max_time TIME DEFAULT \'NULL\', CHANGE thu_time thu_time TIME DEFAULT \'NULL\', CHANGE thu_min_time thu_min_time TIME DEFAULT \'NULL\', CHANGE thu_max_time thu_max_time TIME DEFAULT \'NULL\', CHANGE fri_time fri_time TIME DEFAULT \'NULL\', CHANGE fri_min_time fri_min_time TIME DEFAULT \'NULL\', CHANGE fri_max_time fri_max_time TIME DEFAULT \'NULL\', CHANGE sat_time sat_time TIME DEFAULT \'NULL\', CHANGE sat_min_time sat_min_time TIME DEFAULT \'NULL\', CHANGE sat_max_time sat_max_time TIME DEFAULT \'NULL\', CHANGE sun_time sun_time TIME DEFAULT \'NULL\', CHANGE sun_min_time sun_min_time TIME DEFAULT \'NULL\', CHANGE sun_max_time sun_max_time TIME DEFAULT \'NULL\', CHANGE mon_margin_duration mon_margin_duration INT DEFAULT NULL, CHANGE tue_margin_duration tue_margin_duration INT DEFAULT NULL, CHANGE wed_margin_duration wed_margin_duration INT DEFAULT NULL, CHANGE thu_margin_duration thu_margin_duration INT DEFAULT NULL, CHANGE fri_margin_duration fri_margin_duration INT DEFAULT NULL, CHANGE sat_margin_duration sat_margin_duration INT DEFAULT NULL, CHANGE sun_margin_duration sun_margin_duration INT DEFAULT NULL, CHANGE max_detour_duration max_detour_duration INT DEFAULT NULL, CHANGE max_detour_distance max_detour_distance INT DEFAULT NULL, CHANGE multi_transport_mode multi_transport_mode TINYINT(1) DEFAULT \'NULL\', CHANGE price_km price_km NUMERIC(4, 2) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE direction CHANGE ascend ascend INT DEFAULT NULL, CHANGE descend descend INT DEFAULT NULL, CHANGE bbox_min_lon bbox_min_lon NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_min_lat bbox_min_lat NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_max_lon bbox_max_lon NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_max_lat bbox_max_lat NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE geo_json_bbox geo_json_bbox POLYGON DEFAULT \'NULL\' COMMENT \'(DC2Type:polygon)\', CHANGE bearing bearing INT DEFAULT NULL, CHANGE geo_json_detail geo_json_detail LINESTRING DEFAULT \'NULL\' COMMENT \'(DC2Type:linestring)\'');
        $this->addSql('ALTER TABLE event CHANGE url url VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE image CHANGE event_id event_id INT DEFAULT NULL, CHANGE community_id community_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE relay_point_id relay_point_id INT DEFAULT NULL, CHANGE relay_point_type_id relay_point_type_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE alt alt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE crop_x1 crop_x1 INT DEFAULT NULL, CHANGE crop_y1 crop_y1 INT DEFAULT NULL, CHANGE crop_x2 crop_x2 INT DEFAULT NULL, CHANGE crop_y2 crop_y2 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mass CHANGE analyzing_date analyzing_date DATETIME DEFAULT \'NULL\', CHANGE analyzed_date analyzed_date DATETIME DEFAULT \'NULL\', CHANGE calculation_date calculation_date DATETIME DEFAULT \'NULL\', CHANGE calculated_date calculated_date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE mass_person CHANGE given_name given_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE family_name family_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE bbox_min_lon bbox_min_lon NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_min_lat bbox_min_lat NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_max_lon bbox_max_lon NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bbox_max_lat bbox_max_lat NUMERIC(10, 6) DEFAULT \'NULL\', CHANGE bearing bearing INT DEFAULT NULL, CHANGE outward_time outward_time TIME DEFAULT \'NULL\', CHANGE return_time return_time TIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE message CHANGE message_id message_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE notification CHANGE template_title template_title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE template_body template_body VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE active active TINYINT(1) DEFAULT \'NULL\', CHANGE active_default active_default TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE notified CHANGE proposal_id proposal_id INT DEFAULT NULL, CHANGE matching_id matching_id INT DEFAULT NULL, CHANGE ask_history_id ask_history_id INT DEFAULT NULL, CHANGE recipient_id recipient_id INT DEFAULT NULL, CHANGE sent_date sent_date DATETIME DEFAULT \'NULL\', CHANGE received_date received_date DATETIME DEFAULT \'NULL\', CHANGE read_date read_date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE paragraph CHANGE section_id section_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE proposal DROP FOREIGN KEY FK_BFE5947223107D10');
        $this->addSql('DROP INDEX IDX_BFE5947223107D10 ON proposal');
        $this->addSql('ALTER TABLE proposal DROP user_delegate_id, CHANGE proposal_linked_id proposal_linked_id INT DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE criteria_id criteria_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ptarrival CHANGE individual_stop_id individual_stop_id INT DEFAULT NULL, CHANGE name name VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ptdeparture CHANGE individual_stop_id individual_stop_id INT DEFAULT NULL, CHANGE name name VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ptjourney CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE price price NUMERIC(4, 2) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE ptleg CHANGE ptjourney_id ptjourney_id INT DEFAULT NULL, CHANGE ptdeparture_id ptdeparture_id INT DEFAULT NULL, CHANGE ptarrival_id ptarrival_id INT DEFAULT NULL, CHANGE travel_mode_id travel_mode_id INT DEFAULT NULL, CHANGE ptline_id ptline_id INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE magnetic_direction magnetic_direction VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE relative_direction relative_direction VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE direction direction VARCHAR(45) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ptline CHANGE ptcompany_id ptcompany_id INT DEFAULT NULL, CHANGE travel_mode_id travel_mode_id INT DEFAULT NULL, CHANGE number number VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE origin origin VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE destination destination VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE direction direction VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE transport_mode transport_mode INT DEFAULT NULL, CHANGE color color VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE ptstep CHANGE ptleg_id ptleg_id INT DEFAULT NULL, CHANGE ptdeparture_id ptdeparture_id INT DEFAULT NULL, CHANGE ptarrival_id ptarrival_id INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE duration duration INT DEFAULT NULL, CHANGE magnetic_direction magnetic_direction VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE relative_direction relative_direction VARCHAR(10) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE recipient CHANGE sent_date sent_date DATETIME DEFAULT \'NULL\', CHANGE read_date read_date DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE relay_point CHANGE community_id community_id INT DEFAULT NULL, CHANGE private private TINYINT(1) DEFAULT \'NULL\', CHANGE places places SMALLINT DEFAULT NULL, CHANGE places_disabled places_disabled SMALLINT DEFAULT NULL, CHANGE free free TINYINT(1) DEFAULT \'NULL\', CHANGE secured secured TINYINT(1) DEFAULT \'NULL\', CHANGE official official TINYINT(1) DEFAULT \'NULL\', CHANGE suggested suggested TINYINT(1) DEFAULT \'NULL\', CHANGE permalink permalink VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE role CHANGE parent_id parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE section CHANGE article_id article_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE sub_title sub_title VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE uright CHANGE parent_id parent_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE user ADD pupdtime DATETIME DEFAULT \'NULL\', DROP pwd_token_date, CHANGE given_name given_name VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE family_name family_name VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE password password VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE nationality nationality VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE birth_date birth_date DATE DEFAULT \'NULL\', CHANGE telephone telephone VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE max_detour_duration max_detour_duration INT DEFAULT NULL, CHANGE max_detour_distance max_detour_distance INT DEFAULT NULL, CHANGE any_route_as_passenger any_route_as_passenger TINYINT(1) DEFAULT \'NULL\', CHANGE multi_transport_mode multi_transport_mode TINYINT(1) DEFAULT \'NULL\', CHANGE pwd_token pwd_token VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE geo_token geo_token VARCHAR(100) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, CHANGE language language VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE user_right CHANGE territory_id territory_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_role CHANGE territory_id territory_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE waypoint CHANGE proposal_id proposal_id INT DEFAULT NULL, CHANGE matching_id matching_id INT DEFAULT NULL, CHANGE ask_id ask_id INT DEFAULT NULL');
    }
}
