<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200215143800 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('
            UPDATE `role` SET `title`=\'Super admin\', `name`=\'ROLE_SUPER_ADMIN\', `parent_id`=NULL WHERE `id`=1;
            UPDATE `role` SET `title`=\'Admin\', `name`=\'ROLE_ADMIN \', `parent_id`=1 WHERE `id`=2;
            UPDATE `role` SET `title`=\'User with full registration\', `name`=\'ROLE_USER_REGISTERED_FULL \', `parent_id`=2 WHERE `id`=3;
            UPDATE `role` SET `title`=\'User with minimal registration\', `name`=\'ROLE_USER_REGISTERED_MINIMAL \', `parent_id`=3 WHERE `id`=4;
            UPDATE `role` SET `title`=\'Unregistered or disconnected user\', `name`=\'ROLE_USER \', `parent_id`=4 WHERE `id`=5;
            UPDATE `role` SET `title`=\'Mobimatch user\', `name`=\'ROLE_MASS_MATCH \', `parent_id`=2 WHERE `id`=6;
            INSERT INTO `role` (`id`, `title`, `name`, `parent_id`) VALUES
            (7,  \'Community manager \',  \'ROLE_COMMUNITY_MANAGER \', 2),
            (8,  \'Solidary manager \',  \'ROLE_SOLIDARY_MANAGER \', 2),
            (9,  \'Communication manager \',  \'ROLE_COMMUNICATION_MANAGER \', 2);
        ');
        $this->addSql('DELETE FROM role_right;');
        $this->addSql('DELETE FROM user_right;');
        $this->addSql('DELETE FROM uright;');
        $this->addSql('
            INSERT INTO `uright` (`id`, `name`, `description`, `object`) VALUES
            (1, \'user_manage\', \'Manage users\', NULL),
            (2, \'user_message_manage\', \'Manage users messages\', NULL),
            (3, \'user_manage_self\', \'Manage its own profile\', \'user\'),
            (4, \'user_message_manage_self\', \'Manage its own messages\', \'user\'),
            (5, \'ad_manage\', \'Manage carpool data\', NULL),
            (6, \'ad_manage_self\', \'Manage its own carpool data\', \'ad\'),
            (7, \'article_manage\', \'Manage articles\', NULL),
            (8, \'community_manage\', \'Manage communities\', NULL),
            (9, \'community_manage_self\', \'Manage its own communities\', \'communityManaged()\'),
            (10, \'event_manage\', \'Manage events\', NULL),
            (11, \'event_manage_self\', \'Manage its own events\', \'event\'),
            (12, \'relay_point_manage\', \'Manage relay points\', NULL),
            (13, \'relay_point_manage_self\', \'Manage its own relay points\', \'relaypoint\'),
            (14, \'territory_manage\', \'Manage territories\', NULL),
            (15, \'mass_manage\', \'Manage mass matching data\', NULL),
            (16, \'mass_manage_self\', \'Manage its own mass matching data\', \'mass\'),
            (17, \'permission_manage\', \'Manage permissions\', NULL),
            (18, \'solidary_manage\', \'Manage solidary data\', NULL),
            (19, \'mass_communication_manage\', \'Manage communication campaigns\', NULL),
            (20, \'mass_communication_manage_self\', \'Manage its own communication campaigns\', \'campaign\'),
            (21, \'user_register\', \'Minimal registration\', NULL),
            (22, \'user_register_full\', \'Full registration\', NULL),
            (23, \'user_create\', \'Create a user\', NULL),
            (24, \'user_read\', \'View a user\', NULL),
            (25, \'user_update\', \'Update a user\', NULL),
            (26, \'user_delete\', \'Delete a user\', NULL),
            (27, \'user_list\', \'View the list of users\', NULL),
            (28, \'user_password\', \'Change user password\', NULL),
            (29, \'user_update_self\', \'Update its own profile\', \'user\'),
            (30, \'user_delete_self\', \'Delete its own profile\', \'user\'),
            (31, \'user_password_self\', \'Change its own password\', \'user\'),
            (32, \'user_message_create\', \'Create a message\', NULL),
            (33, \'user_message_read\', \'Read a message of a user\', NULL),
            (34, \'user_message_delete\', \'Delete a message of a user\', NULL),
            (35, \'user_message_read_self\', \'Read its own messages\', \'message()\'),
            (36, \'user_message_delete_self\', \'Delete its own messages\', \'message\'),
            (37, \'ad_create\', \'Create an ad\', NULL),
            (38, \'ad_read\', \'View a user ad\', NULL),
            (39, \'ad_update\', \'Update an ad for a user\', NULL),
            (40, \'ad_delete\', \'Delete an ad for a user\', NULL),
            (41, \'ad_list\', \'View a list of ads\', NULL),
            (42, \'ad_search_create\', \'Create an unpublished search ad and get the results\', NULL),
            (43, \'ad_results\', \'View the results of an ad\', NULL),
            (44, \'ad_create_delegate\', \'Create an ad for a user\', NULL),
            (45, \'ad_update_self\', \'Update its own ad\', \'ad\'),
            (46, \'ad_delete_self\', \'Delete its own ad\', \'ad\'),
            (47, \'ad_results_self\', \'View the results of its own ad\', \'ad\'),
            (48, \'article_create\', \'Create an article\', NULL),
            (49, \'article_read\', \'Read an article\', NULL),
            (50, \'article_update\', \'Update an article\', NULL),
            (51, \'article_delete\', \'Delete an article\', NULL),
            (52, \'article_list\', \'View the list of articles\', NULL),
            (53, \'community_create\', \'Create a community\', NULL),
            (54, \'community_private_create\', \'Create a private community\', NULL),
            (55, \'community_read\', \'View a community\', NULL),
            (56, \'community_private_read\', \'View a private community\', \'communityJoined()\'),
            (57, \'community_update\', \'Update a community\', NULL),
            (58, \'community_delete\', \'Delete a community\', NULL),
            (59, \'community_list\', \'View the list of communities\', NULL),
            (60, \'community_membership\', \'Manage a community membership\', NULL),
            (61, \'community_membership_self\', \'Manage its managed community membership\', \'communityManaged()\'),
            (62, \'community_update_self\', \'Update its managed community\', \'communityManaged()\'),
            (63, \'community_delete_self\', \'Delete its managed community\', \'communityManaged()\'),
            (64, \'community_join\', \'Join/leave a community\', NULL),
            (65, \'community_join_private\', \'Join/leave a private community\', NULL),
            (66, \'event_create\', \'Create an event\', NULL),
            (67, \'event_read\', \'View an event\', NULL),
            (68, \'event_update\', \'Update an event\', NULL),
            (69, \'event_delete\', \'Delete an event\', NULL),
            (70, \'event_list\', \'View the list of events\', NULL),
            (71, \'event_update_self\', \'Update its own event\', \'event\'),
            (72, \'event_delete_self\', \'Delete its own event\', \'event\'),
            (73, \'relay_point_create\', \'Create a relay point\', NULL),
            (74, \'relay_point_read\', \'View a relay point\', NULL),
            (75, \'relay_point_update\', \'Update a relay point\', NULL),
            (76, \'relay_point_delete\', \'Delete a relay point\', NULL),
            (77, \'relay_point_update_self\', \'Update its own relay point\', \'relaypoint\'),
            (78, \'relay_point_delete_self\', \'Delete its own relay point\', \'relaypoint\'),
            (79, \'relay_point_type_create\', \'Create a relay point type\', NULL),
            (80, \'relay_point_type_read\', \'View a relay point type\', NULL),
            (81, \'relay_point_type_update\', \'Update a relay point type\', NULL),
            (82, \'relay_point_type_delete\', \'Delete a relay point type\', NULL),
            (83, \'relay_point_type_update_self\', \'Update its own relay point type\', \'relaypointtype\'),
            (84, \'relay_point_type_delete_self\', \'Delete its own relay point type\', \'relaypointtype\'),
            (85, \'territory_create\', \'Create a territory\', NULL),
            (86, \'territory_read\', \'Read a territory\', NULL),
            (87, \'territory_update\', \'Update a territory\', NULL),
            (88, \'territory_delete\', \'Delete a territory\', NULL),
            (89, \'mass_create\', \'Create mass matching data\', NULL),
            (90, \'mass_read\', \'Read a mass matching data\', NULL),
            (91, \'mass_delete\', \'Delete mass matching data\', NULL),
            (92, \'mass_read_self\', \'Read its own mass matching data\', \'mass\'),
            (93, \'mass_delete_self\', \'Delete its own mass matching data\', \'mass\'),
            (94, \'solidary_create\', \'Create a solidary record\', NULL),
            (95, \'solidary_read\', \'Read a solidary record\', NULL),
            (96, \'solidary_update\', \'Update a solidary record\', NULL),
            (97, \'solidary_delete\', \'Delete a solidary record\', NULL),
            (98, \'campaign_create\', \'Create a campaign\', NULL),
            (99, \'campaign_read\', \'View a campaign\', NULL),
            (100, \'campaign_update\', \'Update a campaign\', NULL),
            (101, \'campaign_delete\', \'Delete a campaign\', NULL),
            (102, \'campaign_read_self\', \'View its own campaign\', \'campaign\'),
            (103, \'campaign_update_self\', \'Update its own campaign\', \'campaign\'),
            (104, \'campaign_delete_self\', \'Delete its own campaign\', \'campaign\'),
            (105, \'check_permission\', \'Check permission\', NULL),
            (106, \'check_permission_self\', \'Check permission for own objects\', NULL),
            (107, \'access_admin\', \'Get access to administration\', NULL),
            (108, \'communication_contact\', \'Send a contact message\', NULL),
            (109, \'role_assign\', \'Assign a role to a user\', \'role()\'),
            (110, \'right_role_assign\', \'Assign a right to a role\', NULL),
            (111, \'right_user_assign\', \'Assign a right to a user\', NULL);
        ');
        $this->addSql('
            INSERT INTO `right_right` (`right_source`, `right_target`) VALUES
            (23, 1),
            (24, 1),
            (25, 1),
            (25, 29),
            (26, 1),
            (26, 30),
            (27, 1),
            (28, 1),
            (28, 31),
            (29, 3),
            (30, 3),
            (31, 3),
            (32, 4),
            (33, 2),
            (33, 35),
            (34, 2),
            (34, 36),
            (35, 4),
            (36, 4),
            (37, 6),
            (38, 5),
            (39, 5),
            (39, 45),
            (40, 5),
            (40, 46),
            (41, 5),
            (43, 5),
            (43, 47),
            (44, 5),
            (45, 6),
            (46, 6),
            (47, 6),
            (48, 7),
            (50, 7),
            (51, 7),
            (52, 7),
            (53, 9),
            (54, 9),
            (56, 9),
            (57, 8),
            (57, 62),
            (58, 8),
            (58, 63),
            (60, 8),
            (60, 61),
            (61, 9),
            (62, 9),
            (63, 9),
            (64, 9),
            (65, 9),
            (66, 11),
            (67, 71),
            (68, 10),
            (68, 72),
            (69, 10),
            (71, 11),
            (72, 11),
            (73, 13),
            (75, 12),
            (75, 77),
            (76, 12),
            (76, 78),
            (77, 13),
            (78, 13),
            (79, 13),
            (81, 12),
            (81, 83),
            (82, 12),
            (82, 84),
            (83, 13),
            (84, 13),
            (85, 14),
            (86, 14),
            (87, 14),
            (88, 14),
            (89, 16),
            (90, 15),
            (90, 92),
            (91, 15),
            (91, 93),
            (92, 16),
            (93, 16),
            (94, 18),
            (95, 18),
            (96, 18),
            (97, 18),
            (98, 20),
            (99, 19),
            (99, 102),
            (100, 19),
            (100, 103),
            (101, 19),
            (101, 104),
            (102, 20),
            (103, 20),
            (104, 20),
            (105, 106),
            (110, 17),
            (111, 17);
        ');
        $this->addSql('
            INSERT INTO `role_right` (`role_id`, `right_id`) VALUES
            (1, 14),
            (1, 17),
            (2, 1),
            (2, 2),
            (2, 5),
            (2, 7),
            (2, 10),
            (2, 12),
            (2, 15),
            (2, 19),
            (2, 109),
            (3, 9),
            (3, 11),
            (3, 13),
            (4, 3),
            (4, 4),
            (4, 6),
            (5, 21),
            (5, 22),
            (5, 42),
            (5, 49),
            (5, 55),
            (5, 59),
            (5, 67),
            (5, 70),
            (5, 74),
            (5, 80),
            (5, 106),
            (5, 108),
            (6, 16),
            (7, 9),
            (7, 107),
            (8, 18),
            (8, 107),
            (9, 20),
            (9, 107);
        ');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');
    }
}
