<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230530081044 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE mobconnect__long_distance_subscription ADD commitment_proof_journey_id INT DEFAULT NULL, DROP initial_commitment_proof');
        $this->addSql('ALTER TABLE mobconnect__long_distance_subscription ADD CONSTRAINT FK_C928E63E27F7A3F5 FOREIGN KEY (commitment_proof_journey_id) REFERENCES mobconnect__long_distance_journey (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C928E63E27F7A3F5 ON mobconnect__long_distance_subscription (commitment_proof_journey_id)');
        $this->addSql('ALTER TABLE mobconnect__short_distance_subscription ADD commitment_proof_journey_id INT DEFAULT NULL, DROP initial_commitment_proof');
        $this->addSql('ALTER TABLE mobconnect__short_distance_subscription ADD CONSTRAINT FK_5D330FE527F7A3F5 FOREIGN KEY (commitment_proof_journey_id) REFERENCES mobconnect__short_distance_journey (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5D330FE527F7A3F5 ON mobconnect__short_distance_subscription (commitment_proof_journey_id)');
        $this->addSql('ALTER TABLE mobconnect__long_distance_journey DROP commitment_journey');
        $this->addSql('ALTER TABLE mobconnect__short_distance_journey DROP commitment_journey');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE mobconnect__long_distance_journey ADD commitment_journey TINYINT(1) DEFAULT NULL COMMENT \'Status of http request to mobConnect\'');
        $this->addSql('ALTER TABLE mobconnect__long_distance_subscription DROP FOREIGN KEY FK_C928E63E27F7A3F5');
        $this->addSql('DROP INDEX UNIQ_C928E63E27F7A3F5 ON mobconnect__long_distance_subscription');
        $this->addSql('ALTER TABLE mobconnect__long_distance_subscription ADD initial_commitment_proof VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'The autogenerated initial commintment proof\', DROP commitment_proof_journey_id');
        $this->addSql('ALTER TABLE mobconnect__short_distance_journey ADD commitment_journey TINYINT(1) DEFAULT NULL COMMENT \'Status of http request to mobConnect\'');
        $this->addSql('ALTER TABLE mobconnect__short_distance_subscription DROP FOREIGN KEY FK_5D330FE527F7A3F5');
        $this->addSql('DROP INDEX UNIQ_5D330FE527F7A3F5 ON mobconnect__short_distance_subscription');
        $this->addSql('ALTER TABLE mobconnect__short_distance_subscription ADD initial_commitment_proof VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'The autogenerated initial commintment proof\', DROP commitment_proof_journey_id');
    }
}
