monolog:
     handlers:
        main:
            type:               fingers_crossed
            action_level:       info
            handler:            grouped
            channels:           ["!carpool", "!mass", "!geomatcher"]
        grouped:
            type:               group
            members:            [streamed, swift]
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         '%env(MAILER_URL)%'
            to_email:           '%env(MAILER_URL)%'
            subject:            "Oops"
            level:              debug
        user:
            type: stream
            path: "%kernel.logs_dir%/user.log"
            channels: [user]    
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]



