version: '2.4'
services:
  base:
    environment:
      - COMPOSER_PROCESS_TIMEOUT=1200
    image: mobicoop/php-node-chromium:2.0.0
    volumes:
      - ./:/var/www:delegated
      - mobicoop-client-var:/var/www/client/var
      - cache-sync:/root/.cache/
    working_dir: /var/www
    networks:
      - mobicoop_platform
  install:
    extends:
      service: base
    command: npm i
  install-all:
    extends:
      service: base
    command: npm run install-all
  build-admin:
    extends:
      service: base
    working_dir: /var/www/admin
    command: npm run build
  fixtures:
    extends:
      service: base
    working_dir: /var/www/api
    # command: cat /var/www/api/.env
    entrypoint: bash entrypoint.sh 
  doctrine-diff:
    extends:
      service: base
    working_dir: /var/www/api
    command: php bin/console doctrine:migrations:diff -n -v
  doctrine-migrate:
    extends:
      service: base
    working_dir: /var/www/api
    command: php bin/console doctrine:migrations:migrate -n -v

networks:
  mobicoop_platform:
    name: mobicoop_platform

volumes:
  mobicoop-client-var:
  cache-sync: