version: '2.4'
services:
  base:
    environment:
      - COMPOSER_PROCESS_TIMEOUT=1200
    image: mobicoop/php-node-chromium:2.0.0
    volumes:
      - ./:/var/www:delegated
    working_dir: /var/www
    networks:
      - mobicoop_platform
  install:
    extends:
      service: base
    command: npm i
  install-all:
    extends:
      service: base
    command: npm run install-all

networks:
  mobicoop_platform:
    name: mobicoop_platform
