version: "3.8"

services:
  client_php:
    image: registry.gitlab.com/mobicoop/instances/mobicoop-platform/mobicoop-platform-client-php
    container_name: mobicoop_platform_evolution_client_php
    environment:
      APP_ENV: dev
    ports:
      - target: 9001
        published: 9101
        protocol: tcp
      - target: 8079
        published: 8079
    volumes:
      - php_socket_client:/var/run/php
      - ./mobicoop/client/env.dev.local:/srv/client/.env.dev.local
      - ./mobicoop/client/public:/srv/client/public
      - ./mobicoop/client/var:/srv/client/var
      - ./mobicoop/client/mobicoop-platform-client.dev.ini:/usr/local/etc/php/conf.d/mobicoop-platform.ini
    networks:
      - mobicoop_platform
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - api_php

  client_nginx:
    image: registry.gitlab.com/mobicoop/instances/mobicoop-platform/mobicoop-platform-client-nginx
    container_name: mobicoop_platform_evolution_client_nginx
    ports:
      - target: 80
        published: 8081
        protocol: tcp
    volumes:
      - php_socket_client:/var/run/php
      - ./mobicoop/client/public:/srv/client/public:ro
      - ./mobicoop/client/nginx:/var/log/nginx:rw
    networks:
      - mobicoop_platform
    restart: unless-stopped
    depends_on:
      - client_php

  api_php:
    image: registry.gitlab.com/mobicoop/instances/mobicoop-platform/mobicoop-platform-api-php
    container_name: mobicoop_platform_evolution_api_php
    environment:
      APP_ENV: dev
    ports:
      - target: 9000
        published: 9100
        protocol: tcp
    volumes:
      - php_socket_api:/var/run/php
      - ./mobicoop/api/env.dev.local:/srv/api/.env.dev.local
      - ./mobicoop/api/public:/srv/api/public
      - ./mobicoop/api/var:/srv/api/var
      - ./mobicoop/api/mobicoop-platform-api.dev.ini:/usr/local/etc/php/conf.d/mobicoop-platform.ini
    networks:
      - mobicoop_platform
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - db

  api_nginx:
    image: registry.gitlab.com/mobicoop/instances/mobicoop-platform/mobicoop-platform-api-nginx
    container_name: mobicoop_platform_evolution_api_nginx
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    volumes:
      - php_socket_api:/var/run/php
      - ./mobicoop/api/public:/srv/api/public
      - ./mobicoop/api/nginx:/var/log/nginx
    networks:
      - mobicoop_platform
    restart: unless-stopped
    depends_on:
      - api_php

  db:
    image: mariadb:10.4
    #command: --max_allowed_packet=512000000
    container_name: mobicoop_platform_db
    restart: always
    ports: ['3309:3306']
    environment:
      MYSQL_ROOT_PASSWORD: mobicoop
    volumes:
      - ./.mariadb-data:/var/lib/mysql
    networks:
      - mobicoop_platform

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mobicoop_platform_phpmyadmin
    depends_on:
      - db
    environment:
        PMA_PORT: 3309
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: mobicoop
    restart: always
    ports:
        - "8083:80"
    networks:
      - mobicoop_platform

volumes:
  php_socket_api:
  php_socket_client:

networks:
  mobicoop_platform:
    name: mobicoop_platform_network
