version: "3.4"
services:
  mobicoop_platform:
    #image: mobicoop/php-node-chromium
    build: ./
    ports:
      - '9000:9000'
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
    # entrypoint: ["bash", "/var/www/docker/api_bdd_import.sh"]
    entrypoint: bash /var/www/docker/api_entrypoint.sh
    # command: php-fpm7.2 -F
    depends_on:
      - db
    tty: true
    volumes:
      # - .:/application
      - ./api/:/var/www/api:cached
      - ./client/:/var/www/client:cached
      - ./admin/:/var/www/admin:cached

  db:
    image: mariadb:10.4
    container_name: mobicoop_db
    restart: always
    ports: ['3306:3306']
    environment:
      MYSQL_ROOT_PASSWORD: mobicoop
