version: "3.8"

services:
  client_php:
    build:
      context: client
      target: mobicoop_platform_client_php
    container_name: ${CLIENT_PHP_CONTAINER_NAME}
    environment:
      APP_ENV: dev
    ports:
      - target: ${CLIENT_PHP_PORT_TARGET:-9001}
        published: ${CLIENT_PHP_PORT_PUBLISHED:-9101}
        protocol: tcp
      - target: 8079
        published: 8079
    volumes:
      - php_socket_client:/var/run/php
      - ./client:/srv/client:rw
      - ./client/var:/srv/client/var:rw
      - ./client/docker/client/conf.d/mobicoop-platform-client.dev.ini:/usr/local/etc/php/conf.d/mobicoop-platform.ini
    networks:
      - mobicoop_platform
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - api_php

  client_nginx:
    build:
      context: client
      target: mobicoop_platform_client_nginx
    container_name: ${CLIENT_NGINX_CONTAINER_NAME}
    ports:
      - target: ${CLIENT_NGINX_PORT_TARGET:-80}
        published: ${CLIENT_NGINX_PORT_PUBLISHED:-8081}
        protocol: tcp
    volumes:
      - php_socket_client:/var/run/php
      - ./client/public:/srv/client/public:ro
      - ./client/nginx/logs:/var/log/nginx:rw
    networks:
      - mobicoop_platform
    restart: unless-stopped
    depends_on:
      - client_php

  api_php:
    build:
      context: api
      target: mobicoop_platform_api_php
    container_name: ${API_PHP_CONTAINER_NAME}
    environment:
      APP_ENV: dev
    ports:
      - target: ${API_PHP_PORT_TARGET:-9000}
        published: ${API_PHP_PORT_PUBLISHED:-9100}
        protocol: tcp
    volumes:
      - php_socket_api:/var/run/php
      - ./api:/srv/api:rw
      - ./api/var:/srv/api/var:rw
      - ./api/docker/api/conf.d/mobicoop-platform-api.dev.ini:/usr/local/etc/php/conf.d/mobicoop-platform.ini
    networks:
      - mobicoop_platform
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - db

  api_nginx:
    build:
      context: api
      target: mobicoop_platform_api_nginx
    container_name: ${API_NGINX_CONTAINER_NAME}
    ports:
      - target: ${API_NGINX_PORT_TARGET:-80}
        published: ${API_NGINX_PORT_PUBLISHED:-8080}
        protocol: tcp
    volumes:
      - php_socket_api:/var/run/php
      - ./api/public:/srv/api/public:ro
      - ./api/nginx/logs:/var/log/nginx:rw
    networks:
      - mobicoop_platform
    restart: unless-stopped
    depends_on:
      - api_php

  db:
    image: mariadb:10.4
    #command: --max_allowed_packet=512000000
    container_name: mobicoop_platform_db
    restart: always
    ports: ['3309:3306']
    environment:
      MYSQL_ROOT_PASSWORD: mobicoop
    volumes:
      - ./.mariadb-data:/var/lib/mysql
    networks:
      - mobicoop_platform

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mobicoop_platform_phpmyadmin
    depends_on:
      - db
    environment:
        PMA_PORT: 3309
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: mobicoop
    restart: always
    ports:
        - "8083:80"
    networks:
      - mobicoop_platform

volumes:
  php_socket_api:
  php_socket_client:

networks:
  mobicoop_platform:
    name: mobicoop_platform_network
