api_platform:

    # The title of the API.
    title: 'Mobicoop API'

    # The description of the API.
    description: 'The mobility API.'

    # The version of the API.
    version: '0.1.0'

    # we disable the original swagger to change the path of the documentation
    enable_swagger_ui: false
    
    # enable token bearer
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header

    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/src/Carpool/Entity','%kernel.project_dir%/src/User/Entity',
            '%kernel.project_dir%/src/PublicTransport/Entity','%kernel.project_dir%/src/Geography/Entity','%kernel.project_dir%/src/Travel/Entity',
            '%kernel.project_dir%/src/ExternalJourney/Entity','%kernel.project_dir%/src/Rdex/Entity','%kernel.project_dir%/src/Event/Entity',
            '%kernel.project_dir%/src/Image/Entity']
            
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Carpool/Entity'
        - '%kernel.project_dir%/src/User/Entity'
        - '%kernel.project_dir%/src/PublicTransport/Entity'
        - '%kernel.project_dir%/src/ExternalJourney/Entity'
        - '%kernel.project_dir%/src/Geography/Entity'
        - '%kernel.project_dir%/src/Travel/Entity'
        - '%kernel.project_dir%/src/Rdex/Entity'
        - '%kernel.project_dir%/src/Event/Entity'
        - '%kernel.project_dir%/src/Image/Entity'
        
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']