api_platform:

    # The title of the API.
    title: 'Coviride API'

    # The description of the API.
    description: 'The carpooling API.'

    # The version of the API.
    version: '0.1.0'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/src/Address/Entity','%kernel.project_dir%/src/Carpool/Entity','%kernel.project_dir%/src/User/Entity',
            '%kernel.project_dir%/src/PublicTransport/Entity',
            '%kernel.project_dir%/src/ExternalJourney/Entity',
            '%kernel.project_dir%/src/Rdex/Entity']
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Address/Entity'
        - '%kernel.project_dir%/src/Carpool/Entity'
        - '%kernel.project_dir%/src/User/Entity'
        - '%kernel.project_dir%/src/PublicTransport/Entity'
        - '%kernel.project_dir%/src/ExternalJourney/Entity'
        - '%kernel.project_dir%/src/Rdex/Entity'
        
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        html:     ['text/html']