parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\App\Entity'
                alias: App
            Carpool:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Carpool/Entity'
                prefix: 'App\Carpool\Entity'
                alias: Carpool
            Community:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Community/Entity'
                prefix: 'App\Community\Entity'
                alias: Community
            Event:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Event/Entity'
                prefix: 'App\Event\Entity'
                alias: Event
            Geography:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Geography/Entity'
                prefix: 'App\Geography\Entity'
                alias: Geography
            Image:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Image/Entity'
                prefix: 'App\Image\Entity'
                alias: Image
            Match:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Match/Entity'
                prefix: 'App\Match\Entity'
                alias: Match
            PublicTransport:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/PublicTransport/Entity'
                prefix: 'App\PublicTransport\Entity'
                alias: PublicTransport
            RelayPoint:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/RelayPoint/Entity'
                prefix: 'App\RelayPoint\Entity'
                alias: RelayPoint
            Right:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Right/Entity'
                prefix: 'App\Right\Entity'
                alias: Right
            Travel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Travel/Entity'
                prefix: 'App\Travel\Entity'
                alias: Travel
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: User