knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(resolve:WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
    process_timeout: 1200 # In seconds    