framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations_client'
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
