vich_uploader:
    db_driver: orm

    mappings:

        # mapping for event images
        event:
            uri_prefix: /upload/events/images/
            upload_destination: '%kernel.project_dir%/public/upload/events/images/'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}

        # mapping for communities images
        community:
            uri_prefix: /upload/communities/images/
            upload_destination: '%kernel.project_dir%/public/upload/communities/images/'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}
        
        # mapping for user images (avatar)
        user:
            uri_prefix: /upload/users/images/
            upload_destination: '%kernel.project_dir%/public/upload/users/images/' 
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}   
        
        # mapping for mass import files
        mass:
            uri_prefix: /upload/mass/files/
            upload_destination: '%kernel.project_dir%/public/upload/mass/files/'  
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}  

        # mapping for mass communication images
        masscommunication:
            uri_prefix: /upload/masscommunication/images/
            upload_destination: '%kernel.project_dir%/public/upload/masscommunication/images/' 
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}

        # mapping for solidary proof files
        solidary:
            uri_prefix: /upload/solidary/proofs/
            upload_destination: '%kernel.project_dir%/public/upload/solidary/proofs/'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}