vich_uploader:
    db_driver: orm

    mappings:
        event:
            uri_prefix: /upload/event/images/
            upload_destination: '%kernel.project_dir%/public/upload/event/images/'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'fileName'}
        user:
            uri_prefix: /upload/user/images/
            upload_destination: '%kernel.project_dir%/public/upload/user/images/'    