###############
# user routes #
###############

# login
user_login:
    path:
        fr: /utilisateur/connexion
        en: /user/login
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::login

# sign up
user_sign_up:
    path:
        fr: /utilisateur/inscription
        en: /user/signup
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userSignUp

# create proposal
user_proposal_create:
    path:
        fr: /utilisateur/annonce/partager
        en: /user/proposal/create
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProposalCreate

# profile
user_profile:
    path:
        fr: /utilisateur/profil
        en: /user/profile
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfile

# messages
user_messages:
    path:
        fr: /utilisateur/messages
        en: /user/messages
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfile

# profile update
user_profile_update:
    path:
        fr: /utilisateur/profil/modifier
        en: /user/profile/update
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfileUpdate

# password update
user_password_update:
    path:
        fr: /utilisateur/mot-de-passe/modifier
        en: /user/password/update
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userPasswordUpdate

# profile delete
user_profile_delete:
    path:
        fr: /utilisateur/profil/supprimer
        en: /user/profile/delete
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfileDelete

# logout
logout:
    path: /user/logout
    
##################
# carpool routes #
##################
# messages
ad:
    path:
        fr: /covoiturage/annonce/poster
        en: /carpool/ad/share
    controller: Mobicoop\Bundle\MobicoopBundle\Carpool\Controller\CarpoolController::ad