image: tetraweb/php

stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y zip unzip wget
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    # Install Xdebug
    - pecl install xdebug
    # Enable Xdebug
    - docker-php-ext-enable xdebug

job 2:
  stage: test
  script:
    - composer install
    - npm install
    - npm run postinstall
    - npx encore dev
    - npm run testAndCoverage
      
job 3:
  stage: deploy
  script:
    - npm run postinstall
    - npm run generateDoc
  artifacts:
    paths:
    - public
  only:
  - branches
