image: misterio92/ci-php-node

stages:
  - build
  - test
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules
  - vendor

build:linux:
  stage: build
  before_script:
    - composer install
    - npm install
    - npm run postinstall
  script:
    - npx encore dev
    - npm run generateDoc
  artifacts:
    paths:
      - public

test:linux:
  stage: test
  script:
    - npm run testAndCoverage
  dependencies:
    - build:linux
      
pages:
  stage: deploy
  script:
    - echo 'Deploying the doc...'
    - ls -alh
    - ls -alh vendor/bin
    - ls -alh public/build
    - ls -alh public/build/doc
  dependencies:
    - build:linux
  artifacts:
    paths:
    - public
  only:
  - master
