image: tetraweb/php

before_script:
  - apt-get update
  - apt-get install zip unzip wget
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"

test:coviride:
    before_script:
      - apt-get install wget
      # Install Xdebug
      - pecl install xdebug
      # Enable Xdebug
      - docker-php-ext-enable xdebug
      - composer install
      - npm install
      - npm run postinstall
      - npx encore dev
    script:
      - npm run testAndCoverage

pages:
  stage: deploy
  script:
    - npm run postinstall
    - npm run generateDoc
  artifacts:
    paths:
    - public
  only:
  - tags
