image: tetraweb/php

stages:
  - build
  - test

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules
  - vendor

build:linux:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y zip unzip wget
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - composer install
    - npm install
    - npm run postinstall
    - npm run generateDoc
  script:
    - npx encore dev
  artifacts:
    paths:
      - public

test:linux:
  stage: test
  before_script:
    # Install Xdebug
    - pecl install xdebug
    # Enable Xdebug
    - docker-php-ext-enable xdebug
  script:
    - npm run testAndCoverage
  dependencies:
    - build:linux
      
pages:
  script:
    - echo 'Deploying the doc...'
    - ls -alh
    - ls -alh vendor/bin
    - ls -alh public/build
    - ls -alh public/build/doc
  dependencies:
    - build:linux
  artifacts:
    paths:
    - public
  only:
  - master
