image: tetraweb/php

stages:
  - build
  - test
  - deploy

build:linux:
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -y zip unzip wget
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    # Install Xdebug
    - pecl install xdebug
    # Enable Xdebug
    - docker-php-ext-enable xdebug
    - composer install
    - npm install
    - npm run postinstall
  script:
    - npx encore dev
  artifacts:
    paths:
      - vendor
      - node_modules
      - public

test:linux:
  stage: test
  script:
    - npm run testAndCoverage
  dependencies:
    - build:linux
      
job 3:
  stage: deploy
  script:
    - npm run postinstall
    - npm run generateDoc
  dependencies:
    - build:linux
  artifacts:
    paths:
    - public
  only:
  - branches
