# configuration file for image resizing
parameters:
    images:
        # configuration for events
        event:
            # upload folders
            folder:
                base: 'upload/'
                plain: 'events/images/'
                versions: 'events/images/versions/'
            # versions to generate
            versions:
                # versions sizes to be generated
                # - filterSet : the LiipImagine filter set to apply
                # - prefix : the prefix of the version
                - {filterSet: 'max', prefix: ''}
                - {filterSet: 'square_800', prefix: '800-'}
                - {filterSet: 'square_250', prefix: '250-'}
                - {filterSet: 'square_100', prefix: '100-'}