app_annotations:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../src/MobicoopBundle/Controller/'
    type:     annotation
    
geography_annotations:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../src/MobicoopBundle/Geography/Controller/'
    type:     annotation
    
#user_annotations:
    # loads routes from the PHP annotations of the controllers found in that directory
    #resource: '../src/MobicoopBundle/User/Controller/'
    #type:     annotation



###############
# user routes #
###############

# login
user_login:
    path:
        fr: /utilisateur/connexion
        en: /user/login
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::login

# sign up
user_sign_up:
    path:
        fr: /utilisateur/inscription
        en: /user/signup
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userSignUp

# create proposal
user_proposal_create:
    path:
        fr: /utilisateur/annonce/partager
        en: /user/proposal/create
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProposalCreate

# profile
user_profile:
    path:
        fr: /utilisateur/profil
        en: /user/profile
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfile

# profile
user_messages:
    path:
        fr: /utilisateur/messages
        en: /user/messages
    controller: Mobicoop\Bundle\MobicoopBundle\User\Controller\UserController::userProfile


# logout
logout:
    path: /user/logout