twig:
    paths:
        '%kernel.project_dir%/templates': Mobicoop
        '%kernel.project_dir%/src/MobicoopBundle/Resources/views': Bundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    globals:
        delete_profile: '%env(DELETE_PROFILE)%'
        app_name: '%env(APP_NAME)%'
        assets_prefix: '%env(ASSETS_PREFIX)%'
        geoCompleteUri: '%env(GEOCOMPLETE_URI)%'
        ageMin: '%env(USER_MIN_AGE)%'
        ageMax: '%env(USER_MAX_AGE)%'
        priceKm: '%env(CARPOOL_PRICE)%'
        marginDuration: '%env(CARPOOL_MARGIN_DURATION)%'
        searchRegular: '%env(bool:CARPOOL_SEARCH_REGULAR)%'
        searchPunctualDate: '%env(bool:CARPOOL_PUNCTUAL_DATE_OPTIONAL)%'
        adRegular: '%env(bool:CARPOOL_AD_REGULAR)%'
        distinguishRegular: '%env(bool:CARPOOL_DISTINGUISH_REGULAR)%'
        mapProvider: '%env(resolve:MAP_PROVIDER)%'
        urlTiles: '%env(resolve:MAP_URL_TILES)%'
        attributionCopyright: '%env(resolve:MAP_ATTRIBUTION_COPYRIGHTS)%'
        communityAvatarSize: '%env(resolve:COMMUNITY_AVATAR_SIZE)%'
        communityAvatarVersion: '%env(resolve:COMMUNITY_AVATAR_VERSION)%'
        urlAltCommunityAvatar: '%env(resolve:URL_ALT_COMMUNITY_AVATAR)%'
        dataComponents: '%env(resolve:DATA_COMPONENTS)%'
        homeCommunityDisplay: '%env(resolve:COMMUNITY_DISPLAY)%'
        additionalTextDisplay: '%env(resolve:ADDITIONAL_TEXT_DISPLAY)%'
        shareAdButtonDisplay: '%env(bool:SHARE_AD_BUTTON_DISPLAY)%'
        homeEventDisplay: '%env(resolve:EVENT_DISPLAY)%'
        homeSolidaryDisplay: '%env(resolve:SOLIDARY_DISPLAY)%'
        userAvatarSize: '%env(resolve:USER_AVATAR_SIZE)%'
        carpoolerRate: '%env(resolve:CARPOOLER_RATE)%'
        eventImageSize : '%env(resolve:EVENT_IMAGE_SIZE)%'
        matomoUrl: '%env(resolve:MATOMO_URL)%'
        matomoSiteId: '%env(resolve:MATOMO_SITE_ID)%'
        urlMobile: '%env(resolve:URL_MOBILE)%'
        urlAdmin: '%env(resolve:URL_ADMIN)%'
        canAccessAdminFromCommunity: '%env(resolve:CAN_ACCESS_ADMIN_FROM_COMMUNITY)%'
        timePrecision: '%env(TIME_PRECISION)%'
