twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    # themes used in the project (the order is important : each theme overrides the previous ones) 
    form_themes:
    - '@Mobicoop/form/mobicoop.html.twig'
    globals:
        delete_profile: '%env(DELETE_PROFILE)%'
        app_name: '%env(APP_NAME)%'
        assets_prefix: '%env(ASSETS_PREFIX)%'
        geoCompleteUri: '%env(GEOCOMPLETE_URI)%'