twig:
    paths: 
        '%kernel.project_dir%/templates': Mobicoop
        '%kernel.project_dir%/src/MobicoopBundle/Resources/views': Bundle 
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    # themes used in the project (the order is important : each theme overrides the previous ones) 
    form_themes:
    - '@Mobicoop/form/mobicoop.html.twig'
    globals:
        delete_profile: '%env(DELETE_PROFILE)%'
        app_name: '%env(APP_NAME)%'
        assets_prefix: '%env(ASSETS_PREFIX)%'
        geoCompleteUri: '%env(GEOCOMPLETE_URI)%'
        ageMin: '%env(USER_MIN_AGE)%'
        ageMax: '%env(USER_MAX_AGE)%'
        priceKm: '%env(CARPOOL_PRICE)%'
        marginTime: '%env(CARPOOL_MARGIN_TIME)%'
        urlTiles: '%env(resolve:URL_TILES)%'
        attributionCopyright: '%env(resolve:ATTRIBUTION_COPYRIGHTS)%'